require('impatient')
require('plugins')
require('setup')
require('treesitter')
require('lsp')
require('keymap')

require('plugins.nerdtree')
require('plugins.telescope')
require('plugins.vim-airline')
require('plugins.vim-go')
